use rdkafka::config::ClientConfig;
use rdkafka::producer::{FutureProducer, FutureRecord};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tokio::time::sleep;

// This pulls in the Protobuf code generated by build.rs
pub mod lumenlog {
    include!(concat!(env!("OUT_DIR"), "/lumenlog.rs"));
}
use lumenlog::LogEvent;
use prost::Message; 

#[tokio::main]
async fn main() {
    // Connect to Redpanda (using the service name from docker-compose)
    let producer: FutureProducer = ClientConfig::new()
        .set("bootstrap.servers", "localhost:9092")
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Producer creation error");

    println!("Rust Agent Live! Sending logs to Redpanda...");

    loop {
        let timestamp = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos() as i64;

        let log = LogEvent {
            service_name: "rust-agent".to_string(),
            host: "dev-container".to_string(),
            level: "INFO".to_string(),
            message: "System Heartbeat - All systems nominal".to_string(),
            timestamp,
            metadata: std::collections::HashMap::new(),
        };

        // Serialize to binary Protobuf
        let mut buf = Vec::new();
        log.encode(&mut buf).unwrap();

        // Push to the 'logs-raw' topic
        let record = FutureRecord::to("logs-raw")
            .payload(&buf)
            .key("heartbeat");

        match producer.send(record, Duration::from_secs(0)).await {
            Ok(_) => println!("✔ Log sent at {}", timestamp),
            Err((e, _)) => eprintln!("Failed to send log: {:?}", e),
        }

        sleep(Duration::from_secs(1)).await;
    }
}